# Generated by Django 3.2.13 on 2022-06-28 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodCategory', models.CharField(choices=[('분식', '분식'), ('피자', '피자'), ('치킨', '치킨'), ('양식', '양식'), ('백반·죽·국수', '백반·죽·국수'), ('고기·구이', '고기·구이'), ('족발·보쌈', '족발·보쌈'), ('중식', '중식'), ('돈까스·회·일식', '돈까스·회·일식'), ('찜·찌개·탕', '찜·찌개·탕'), ('카페·디저트', '카페·디저트'), ('패스트푸드', '패스트푸드')], max_length=20, null=True)),
                ('name', models.CharField(max_length=10)),
                ('rate', models.FloatField(null=True)),
                ('tel', models.CharField(max_length=15, null=True)),
                ('min', models.IntegerField()),
                ('delivery_time', models.IntegerField()),
                ('delivery_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menus', models.JSONField(default=dict)),
                ('total', models.IntegerField(default=0)),
                ('host_option', models.CharField(choices=[('time', 'time'), ('button', 'button'), ('count', 'count')], max_length=10)),
                ('option_num', models.IntegerField(null=True)),
                ('pay_option', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.store')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('info', models.CharField(max_length=30, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.store')),
            ],
        ),
    ]
