# Generated by Django 4.0.5 on 2022-06-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='info',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='host_option',
            field=models.CharField(choices=[('button', 'button'), ('time', 'time'), ('count', 'count')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('주문완료', '주문완료'), ('주문중', '주문중'), ('결제전', '결제전')], default='결제전', max_length=10),
        ),
        migrations.AlterField(
            model_name='store',
            name='foodCategory',
            field=models.CharField(choices=[('치킨', '치킨'), ('족발·보쌈', '족발·보쌈'), ('백반·죽·국수', '백반·죽·국수'), ('카페·디저트', '카페·디저트'), ('패스트푸드', '패스트푸드'), ('분식', '분식'), ('중식', '중식'), ('양식', '양식'), ('돈까스·회·일식', '돈까스·회·일식'), ('고기·구이', '고기·구이'), ('찜·찌개·탕', '찜·찌개·탕'), ('피자', '피자')], max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='store',
            name='tel',
            field=models.CharField(max_length=30),
        ),
    ]
