# Generated by Django 4.0.4 on 2022-06-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='host_option',
            field=models.CharField(choices=[('time', 'time'), ('count', 'count'), ('button', 'button')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='menus',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='order',
            name='users',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='store',
            name='foodCategory',
            field=models.CharField(choices=[('패스트푸드', '패스트푸드'), ('중식', '중식'), ('돈까스·회·일식', '돈까스·회·일식'), ('피자', '피자'), ('찜·찌개·탕', '찜·찌개·탕'), ('치킨', '치킨'), ('분식', '분식'), ('양식', '양식'), ('카페·디저트', '카페·디저트'), ('고기·구이', '고기·구이'), ('백반·죽·국수', '백반·죽·국수'), ('족발·보쌈', '족발·보쌈')], max_length=20, null=True),
        ),
    ]
