# Generated by Django 4.0.3 on 2022-06-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='host_option',
            field=models.CharField(choices=[('button', 'button'), ('time', 'time'), ('count', 'count')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('주문중', '주문중'), ('주문완료', '주문완료')], default='주문중', max_length=10),
        ),
        migrations.AlterField(
            model_name='store',
            name='foodCategory',
            field=models.CharField(choices=[('패스트푸드', '패스트푸드'), ('백반·죽·국수', '백반·죽·국수'), ('분식', '분식'), ('돈까스·회·일식', '돈까스·회·일식'), ('치킨', '치킨'), ('찜·찌개·탕', '찜·찌개·탕'), ('양식', '양식'), ('중식', '중식'), ('족발·보쌈', '족발·보쌈'), ('카페·디저트', '카페·디저트'), ('고기·구이', '고기·구이'), ('피자', '피자')], max_length=20),
        ),
    ]
