# Generated by Django 4.0.5 on 2022-06-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_host_option_alter_store_foodcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='foodCategory',
            field=models.CharField(choices=[('피자', '피자'), ('돈까스·회·일식', '돈까스·회·일식'), ('치킨', '치킨'), ('중식', '중식'), ('백반·죽·국수', '백반·죽·국수'), ('고기·구이', '고기·구이'), ('족발·보쌈', '족발·보쌈'), ('양식', '양식'), ('찜·찌개·탕', '찜·찌개·탕'), ('카페·디저트', '카페·디저트'), ('패스트푸드', '패스트푸드'), ('분식', '분식')], max_length=20),
        ),
    ]
