# Generated by Django 4.0.5 on 2022-06-29 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_host_option_alter_order_state_and_more'),
        ('order', '0007_alter_order_state_alter_store_foodcategory'),
    ]

    operations = [
    ]
