# Generated by Django 4.0.3 on 2022-06-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_state_alter_store_foodcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='host_option',
            field=models.CharField(choices=[('button', 'button'), ('count', 'count'), ('time', 'time')], max_length=10),
        ),
        migrations.AlterField(
            model_name='store',
            name='foodCategory',
            field=models.CharField(choices=[('치킨', '치킨'), ('족발·보쌈', '족발·보쌈'), ('피자', '피자'), ('양식', '양식'), ('고기·구이', '고기·구이'), ('찜·찌개·탕', '찜·찌개·탕'), ('패스트푸드', '패스트푸드'), ('카페·디저트', '카페·디저트'), ('돈까스·회·일식', '돈까스·회·일식'), ('백반·죽·국수', '백반·죽·국수'), ('중식', '중식'), ('분식', '분식')], max_length=20),
        ),
    ]
