# Generated by Django 4.0.5 on 2022-06-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('completion', '주문완료'), ('ongoing', '주문중')], max_length=10)),
                ('menu', models.CharField(choices=[('찜·찌개·탕', '찜·찌개·탕'), ('카페·디저트', '카페·디저트'), ('백반·죽·국수', '백반·죽·국수'), ('고기·구이', '고기·구이'), ('분식', '분식'), ('피자', '피자'), ('중식', '중식'), ('양식', '양식'), ('족발·보쌈', '족발·보쌈'), ('치킨', '치킨'), ('돈까스·회·일식', '돈까스·회·일식'), ('패스트푸드', '패스트푸드')], max_length=20)),
                ('location', models.CharField(max_length=10)),
                ('store', models.CharField(max_length=10, null=True)),
                ('author', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
