# Generated by Django 4.0.5 on 2022-06-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='menu',
            field=models.CharField(choices=[('고기·구이', '고기·구이'), ('중식', '중식'), ('피자', '피자'), ('분식', '분식'), ('백반·죽·국수', '백반·죽·국수'), ('족발·보쌈', '족발·보쌈'), ('카페·디저트', '카페·디저트'), ('치킨', '치킨'), ('양식', '양식'), ('찜·찌개·탕', '찜·찌개·탕'), ('돈까스·회·일식', '돈까스·회·일식'), ('패스트푸드', '패스트푸드')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('주문완료', '주문완료'), ('주문중', '주문중')], max_length=10),
        ),
    ]
