# Generated by Django 4.0.5 on 2022-06-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_order_menu_alter_order_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('rate', models.CharField(max_length=10, null=True)),
                ('min', models.CharField(max_length=10)),
                ('delivery_time', models.DateTimeField(auto_now=True)),
                ('delivery_price', models.FloatField()),
                ('menu', models.CharField(choices=[('짬뽕', '짬뽕'), ('볶음밥', '볶음밥')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='menu',
            field=models.CharField(choices=[('양식', '양식'), ('카페·디저트', '카페·디저트'), ('패스트푸드', '패스트푸드'), ('치킨', '치킨'), ('분식', '분식'), ('고기·구이', '고기·구이'), ('찜·찌개·탕', '찜·찌개·탕'), ('백반·죽·국수', '백반·죽·국수'), ('돈까스·회·일식', '돈까스·회·일식'), ('피자', '피자'), ('족발·보쌈', '족발·보쌈'), ('중식', '중식')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('주문중', '주문중'), ('주문완료', '주문완료')], max_length=10),
        ),
    ]
