# Generated by Django 4.0.5 on 2022-06-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_order_menu_alter_store_delivery_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='menu',
            field=models.CharField(choices=[('피자', '피자'), ('찜·찌개·탕', '찜·찌개·탕'), ('중식', '중식'), ('고기·구이', '고기·구이'), ('돈까스·회·일식', '돈까스·회·일식'), ('족발·보쌈', '족발·보쌈'), ('분식', '분식'), ('치킨', '치킨'), ('카페·디저트', '카페·디저트'), ('양식', '양식'), ('백반·죽·국수', '백반·죽·국수'), ('패스트푸드', '패스트푸드')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('주문완료', '주문완료'), ('주문중', '주문중')], max_length=10),
        ),
        migrations.AlterField(
            model_name='store',
            name='delivery_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='min',
            field=models.IntegerField(),
        ),
    ]
