# Generated by Django 4.0.5 on 2022-06-28 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_order_menu_alter_order_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='menu',
        ),
        migrations.AddField(
            model_name='store',
            name='tel',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='menu',
            field=models.CharField(choices=[('피자', '피자'), ('양식', '양식'), ('고기·구이', '고기·구이'), ('중식', '중식'), ('찜·찌개·탕', '찜·찌개·탕'), ('족발·보쌈', '족발·보쌈'), ('치킨', '치킨'), ('백반·죽·국수', '백반·죽·국수'), ('분식', '분식'), ('카페·디저트', '카페·디저트'), ('돈까스·회·일식', '돈까스·회·일식'), ('패스트푸드', '패스트푸드')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('주문중', '주문중'), ('주문완료', '주문완료')], max_length=10),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.store')),
            ],
        ),
    ]
