# Generated by Django 4.0.5 on 2022-06-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_store_menu_store_tel_alter_order_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='foodCategory',
            field=models.CharField(choices=[('중식', '중식'), ('패스트푸드', '패스트푸드'), ('백반·죽·국수', '백반·죽·국수'), ('카페·디저트', '카페·디저트'), ('돈까스·회·일식', '돈까스·회·일식'), ('족발·보쌈', '족발·보쌈'), ('고기·구이', '고기·구이'), ('치킨', '치킨'), ('분식', '분식'), ('찜·찌개·탕', '찜·찌개·탕'), ('양식', '양식'), ('피자', '피자')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='menu',
            field=models.CharField(choices=[('중식', '중식'), ('패스트푸드', '패스트푸드'), ('백반·죽·국수', '백반·죽·국수'), ('카페·디저트', '카페·디저트'), ('돈까스·회·일식', '돈까스·회·일식'), ('족발·보쌈', '족발·보쌈'), ('고기·구이', '고기·구이'), ('치킨', '치킨'), ('분식', '분식'), ('찜·찌개·탕', '찜·찌개·탕'), ('양식', '양식'), ('피자', '피자')], max_length=20),
        ),
    ]
