# Generated by Django 4.0.5 on 2022-06-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_store_foodcategory_alter_order_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='info',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='menu',
            field=models.CharField(choices=[('양식', '양식'), ('찜·찌개·탕', '찜·찌개·탕'), ('고기·구이', '고기·구이'), ('패스트푸드', '패스트푸드'), ('백반·죽·국수', '백반·죽·국수'), ('카페·디저트', '카페·디저트'), ('족발·보쌈', '족발·보쌈'), ('중식', '중식'), ('피자', '피자'), ('분식', '분식'), ('돈까스·회·일식', '돈까스·회·일식'), ('치킨', '치킨')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('주문완료', '주문완료'), ('주문중', '주문중')], max_length=10),
        ),
        migrations.AlterField(
            model_name='store',
            name='foodCategory',
            field=models.CharField(choices=[('양식', '양식'), ('찜·찌개·탕', '찜·찌개·탕'), ('고기·구이', '고기·구이'), ('패스트푸드', '패스트푸드'), ('백반·죽·국수', '백반·죽·국수'), ('카페·디저트', '카페·디저트'), ('족발·보쌈', '족발·보쌈'), ('중식', '중식'), ('피자', '피자'), ('분식', '분식'), ('돈까스·회·일식', '돈까스·회·일식'), ('치킨', '치킨')], max_length=20, null=True),
        ),
    ]
